@startuml "parent-child-2-user-interaction"
' © Sebastian Porto 2016, 
' licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
autonumber "<b>(#)"
participant User #white
participant program #white
participant Main.initialModel as Mim #white
participant Main.view as MV #white
participant Main.update as MU #white
participant Widget.initialModel as Wim #white
participant Widget.view as WV #white
participant Widget.update as WU #white

User -> WV : Click
WV -> MV: Increase
MV -> program: (WidgetMsg Increase)
program -> MU: (WidgetMsg Increase) mainModel
MU -> WU : Increase widgetModel
WU --> MU: (updated widgetModel, command)
MU --> program: (updated mainModel, command)
program -> MV : mainModel
MV -> WV : widgetModel
WV --> MV : Html
MV --> program : Html

@enduml