<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../netstandard/Elmish.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../src/ring.fs" />
    <Compile Include="SubTests.fs" />
    <Compile Include="RingTest.fs" />
    <Compile Include="ProgramTest.fs" />
    <Compile Include="CmdTests.fs" />
    <Compile Include="Attributes.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsCheck" Version="3.3.0" />
    <PackageReference Include="FsCheck.NUnit" Version="3.3.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Unquote" Version="7.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="9.0.300" />
  </ItemGroup>
</Project>