name: .NET

on:
  push:
    branches: [ v4.x ]
  pull_request:
    branches: [ v4.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Build
      run: ./build.fsx
